### ISSUE TITLE
doesn't work anymore  2.14

### ISSUE THREAD

**Issue by sdetweil** [shbatm/MMM-Carousel#31]
**Describe the bug**
two problems.. 
1. now if no position specified for module, its getDom() will never be called.  content not shown, so no point
2. getDom() can return without returning some content.. 
    MUST return SOMETHING, even just empty div
    
    fix  move var div = .. above if clause just before 
    move return div down one line,  outside the if closing brace

**Comment by shbatm** [comment]
Fixed in latest version.

**Comment by majurgens** [comment]
I'm not sure what you mean by "latest version" but I cloned this repo today and still have this problem. As soon as I added `position: "top_bar",` it started working
